{% set name = "conda_version_pkg" %}
{% set version = "custom_conda" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_url: https://github.com/MatthiasKohl/test_conda_version.git

build:
  number: 22
  string: test_22

requirements:
  host:
    - setuptools
    - python
  run:
    - python

test:
  imports:
    - "{{ name|lower }}"

about:
  home: https://rapids.ai/
  summary: test only library
